import type {Metadata} from "next";
import {DM_Serif_Display, Manrope} from "next/font/google";
import "./globals.css";



const dm = DM_Serif_Display({
    variable: "--font-DM-Serif-Display",
    subsets: ["latin"],
    weight: "400",
    display: "swap", // ✅ Qo'shing
});

const manrope = Manrope({
    variable: "--font-Manrope",
    subsets: ["latin"],
    display: "swap", // ✅ Qo'shing
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${dm.variable} ${manrope.variable} antialiased index__bg`}
            suppressHydrationWarning
        >
        {children}
        </body>
        </html>
    );
}
